inputs:
  sdk_hash:
    required: true
    description: "Hash of the generated SDK"
  version_file:
    required: true
    description: "Path to the version file"
  prev_version:
    required: true
    description: "The previous version to increment"

outputs:
  new_version:
    description: "The new incremented version"
    value: ${{ steps.increment.outputs.new_version }}

runs:
  using: "composite"
  steps:
    - name: Increment patch version and update hash
      id: increment
      run: |
        PREV_VERSION="${{ inputs.prev_version }}"
        IFS='.' read -r MAJOR MINOR PATCH <<< "$PREV_VERSION"
        PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        echo "Previous version: $PREV_VERSION"
        echo "New version: $NEW_VERSION"
        sudo sed -i "s/VERSION = .*/VERSION = '$NEW_VERSION'/" "${{ inputs.version_file }}"
        echo "Version updated in file"
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "${{ inputs.sdk_hash }}" > .last_sdk_hash
      shell: bash