inputs:
  sdk_hash:
    required: true
    description: "Hash of the generated SDK"

runs:
  using: "composite"
  steps:
    - name: Increment patch version and update hash
      run: |
        VERSION_FILE="./${{ env.SDK_PATH }}/lib/ragie_ruby_sdk/version.rb"
        if [ -f "$VERSION_FILE" ]; then
          CURRENT_VERSION=$(grep "VERSION = " "$VERSION_FILE" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          sudo sed -i "s/VERSION = .*/VERSION = '$NEW_VERSION'/" "$VERSION_FILE"
        else
          echo "Version file not found: $VERSION_FILE"
          exit 1
        fi
        echo "${{ inputs.sdk_hash }}" > .last_sdk_hash
      shell: bash